// <auto-generated />
using System;
using KonyvAruhaz.Infrastruktura.Adat;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KonyvAruhaz.Infrastruktura.Migrations
{
    [DbContext(typeof(KonyvAruhazDbContext))]
    [Migration("20260304154707_RendelesekEsFelhasznalok")]
    partial class RendelesekEsFelhasznalok
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KonyvAruhaz.Doman.Entitasok.Felhasznalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JelszoHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Szerepkor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Felhasznalok");
                });

            modelBuilder.Entity("KonyvAruhaz.Doman.Entitasok.Kategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriak");
                });

            modelBuilder.Entity("KonyvAruhaz.Doman.Entitasok.Konyv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<decimal>("Ar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriaId");

                    b.ToTable("Konyvek");
                });

            modelBuilder.Entity("KonyvAruhaz.Doman.Entitasok.Rendeles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allapot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FelhasznaloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LetrehozasIdeje")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FelhasznaloId");

                    b.ToTable("Rendelesek");
                });

            modelBuilder.Entity("KonyvAruhaz.Doman.Entitasok.RendelesTetel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EgysegAr")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KonyvId")
                        .HasColumnType("int");

                    b.Property<int>("Mennyiseg")
                        .HasColumnType("int");

                    b.Property<int>("RendelesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KonyvId");

                    b.HasIndex("RendelesId");

                    b.ToTable("RendelesTetelek");
                });

            modelBuilder.Entity("KonyvAruhaz.Doman.Entitasok.Konyv", b =>
                {
                    b.HasOne("KonyvAruhaz.Doman.Entitasok.Kategoria", "Kategoria")
                        .WithMany("Konyvek")
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategoria");
                });

            modelBuilder.Entity("KonyvAruhaz.Doman.Entitasok.Rendeles", b =>
                {
                    b.HasOne("KonyvAruhaz.Doman.Entitasok.Felhasznalo", "Felhasznalo")
                        .WithMany()
                        .HasForeignKey("FelhasznaloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Felhasznalo");
                });

            modelBuilder.Entity("KonyvAruhaz.Doman.Entitasok.RendelesTetel", b =>
                {
                    b.HasOne("KonyvAruhaz.Doman.Entitasok.Konyv", "Konyv")
                        .WithMany()
                        .HasForeignKey("KonyvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KonyvAruhaz.Doman.Entitasok.Rendeles", "Rendeles")
                        .WithMany("Tetelek")
                        .HasForeignKey("RendelesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Konyv");

                    b.Navigation("Rendeles");
                });

            modelBuilder.Entity("KonyvAruhaz.Doman.Entitasok.Kategoria", b =>
                {
                    b.Navigation("Konyvek");
                });

            modelBuilder.Entity("KonyvAruhaz.Doman.Entitasok.Rendeles", b =>
                {
                    b.Navigation("Tetelek");
                });
#pragma warning restore 612, 618
        }
    }
}
